### PR TITLE
Ae/add remove options

### PR DESCRIPTION
**Pull request by anrattanasouk**

### CODE REVIEW

**Comment by anrattanasouk** [comment]
I'm not sure if we are using onDelete right, there's no delete user interaction showing up next to the option

**Comment by ApolloZhu** [comment]
See https://github.com/Fun-Gen/Fun-Gen/pull/46 on how HomeView implemented onDelete

**Comment by anrattanasouk** [comment]
@ApolloZhu Is the way I'm doing it now ok too? Just pushed new changes and then add and remove button works now.
```
Button {
    Task {
        do {
            try await ActivityViewModel.removeOption(optionID, fromActivity: activity.id)
        } catch {
            // TODO: handle error
            print(error)
        }
    }
  } label: {
    Image(systemName: "x.circle")
  }
```
If so I can clean up some comments and then covert this draft to a PR

**Comment by ApolloZhu** [comment]
Sure, that works too. Remember to change the target branch to develop

**Pull request closed without merging**
